name: haskell-formatter
version: "1.0.0"
synopsis: Haskell source code formatter
description: >
  The Haskell Formatter formats Haskell source code. It is strict in that it
  fundamentally rearranges code.
category: Development
author: Benjamin Fischer
maintainer: Benjamin Fischer <benjamin.fischer@evolutics.info>
copyright: (C) 2014–2019 Benjamin Fischer
license: GPL-3
github: evolutics/haskell-formatter.git
extra-source-files:
  - format.sh
  - .gitignore
  - .hlint.yaml
  - README.rst
  - testsuite/resources/examples/default_style.yaml
dependencies:
  - base >= 4.6 && < 5
library:
  source-dirs: src/library
  ghc-options: -Wall
  exposed-modules:
    - Language.Haskell.Formatter
    - Language.Haskell.Formatter.Internal.MapTree
    - Language.Haskell.Formatter.Internal.Newline
    - Language.Haskell.Formatter.Internal.StyleFileFormat
    - Language.Haskell.Formatter.Internal.TreeFormat
  dependencies:
    - containers
    - haskell-src-exts
    - scientific
    - text
    - unordered-containers
    - yaml
executables:
  haskell-formatter:
    main: Main.hs
    source-dirs: src/executable
    ghc-options: -Wall
    dependencies:
      - directory
      - filepath
      - haskell-formatter
      - optparse-applicative
tests:
  test:
    main: Main.hs
    source-dirs: testsuite/src
    ghc-options: -Wall
    dependencies:
      - containers
      - directory-tree
      - doctest
      - filemanip
      - filepath
      - haskell-formatter
      - hlint
      - QuickCheck
      - tasty
      - tasty-hunit
