name: haskell-formatter
version: "1.0.0"
synopsis: Haskell source code formatter
description: >
  The Haskell Formatter formats Haskell source code. It is strict in that it
  fundamentally rearranges code.
category: Development
author: Benjamin Fischer
maintainer: Benjamin Fischer <benjamin.fischer@evolutics.info>
copyright: (C) 2014–2015 Benjamin Fischer
license: GPL-3
github: evolutics/haskell-formatter.git
extra-source-files:
  - .gitignore
  - HLint.hs
  - Makefile
  - README.rst
  - testsuite/resources/examples/default_style.yaml
dependencies:
  - base >= 4.6
library:
  source-dirs: src/library
  ghc-options: -Wall
  exposed-modules:
    - Language.Haskell.Formatter
    - Language.Haskell.Formatter.Internal.MapTree
    - Language.Haskell.Formatter.Internal.Newline
    - Language.Haskell.Formatter.Internal.StyleFileFormat
    - Language.Haskell.Formatter.Internal.TreeFormat
  dependencies:
    - containers >= 0.5
    - haskell-src-exts == 1.16.*
    - scientific >= 0.3
    - text >= 1.0
    - unordered-containers >= 0.2
    - yaml >= 0.8
executables:
  haskell-formatter:
    main: Main.hs
    source-dirs: src/executable
    ghc-options: -Wall
    dependencies:
      - directory >= 1.2
      - filepath >= 1.3
      - haskell-formatter
      - optparse-applicative >= 0.10
tests:
  test:
    main: Main.hs
    source-dirs: testsuite/src
    ghc-options: -Wall
    dependencies:
      - containers >= 0.5
      - directory-tree >= 0.11
      - doctest >= 0.9
      - filemanip >= 0.3
      - filepath >= 1.3
      - haskell-formatter
      - hlint >= 1.9
      - QuickCheck == 2.8.1
      - tasty >= 0.9
      - tasty-hunit >= 0.8
